### PR TITLE
fixes google photos slide show issue

### PR DESCRIPTION
**Pull request by janvda**
Change-type: patch

Fixes issue #56

### CODE REVIEW

**Comment by chrisys** [comment]
Hey @janvda thanks for the contribution... what issue does this resolve?

**Comment by janvda** [comment]
Fixes issue #56

**Comment by chrisys** [comment]
@janvda this isn't passing CI because the commits don't adhere to the contribution guidelines, could you update at least 1 of them then we can get this merged: https://github.com/balena-io-projects/balena-dash/blob/master/CONTRIBUTING.md

**Comment by janvda** [comment]
I have added `Change-type: patch` to the latest commit - which is apparently this pull request.  So, I think this pull request is ready to be merged.

**Comment by janvda** [comment]
To be sure - I added another _cosmetic_ commit with `Change-type: patch`

**Comment by chrisys** [comment]
@balena-ci retest

**Comment by chrisys** [comment]
@janvda nice one! Thanks for the contribution 👍

**Pull request merged**
