### PR TITLE
Correct unmount device `unmount` -> `umount`

### PR DESCRIPTION
**Pull request by tuna-f1sh**
The script isn't actually umounting the drive because it calls the non-existent `unmount` and should call `umount`. Same problem in https://github.com/tmigone/balena-udev-examples/blob/master/usb-copy/copy.sh#L27

Change-type: footer

### CODE REVIEW

**Comment by chrisys** [comment]
@tuna-f1sh thanks for the contribution. As my colleague suggested you need to update the commit message to add the footer, as per the contribution guidelines: https://github.com/balena-io-projects/balena-dash/blob/master/CONTRIBUTING.md

Note that this does have to be the commit message, not the Github description of the PR. 

Once that's done the CI will pass and we can merge!

**Comment by tuna-f1sh** [comment]
Ok amend commit. Sorry, not sure how I mis-read that as PR body.

**Comment by chrisys** [comment]
@tuna-f1sh you've put in `Change-type: footer`, it's in the right place but it should say `Change-type: patch` for a fix such as this.

**Comment by tuna-f1sh** [comment]
Had this first but [first comment](https://github.com/balena-io-projects/balena-dash/pull/58#pullrequestreview-325272225) lead me to believe it was such an insignificant change it was a footnote...anyway, hopefully this is finally mergable!

**Comment by chrisys** [comment]
@balena-ci retest

**Comment by chrisys** [comment]
@tuna-f1sh nice one! Thanks for the contribution! 👍

**Pull request merged**
