### PR TITLE
Added USB stick support for photos container.

### PR DESCRIPTION
**Pull request by tmigone**
Change-type: minor

Hi, i'm opening this PR based of @chrisys feedback on [this](https://forums.balena.io/t/balenadash-usb-stick/22667) post I made on the forums.

I added the option of using a USB stick to provide a photo album for the photos container. 
Please let me know if you want me to do additional testing or work a bit more on it.

### CODE REVIEW

**Comment by dansku** [comment]
@tomasmigone just tested your PR and it's a great addition to the project! thank you!!!

**Comment by dansku** [comment]
@balena-ci retest

**Comment by dansku** [comment]
Hey @tomasmigone, could you change the commit message to add the change-type to the actual commit so that ResinCL manages to generate the right version. 

Let me know if you need any help, thanks!

**Comment by dansku** [comment]
@balena-ci retest

**Comment by dansku** [comment]
@balena-ci retest

**Comment by chrisys** [comment]
@balena-ci retest

**Pull request merged**
